Packer base
Otus-DevOps-2022-02/he110_infra pull request #9
Opened 2022-04-07 20:50 UTC by he110

# Выполнено ДЗ №5

- [x] Основное ДЗ
- [ ] Задание со *

## В процессе сделано:
- Создана сервисная учетка yandex cloud
- Сформирована инструкция для создания образа диска на базе ubuntu 16.04
- Автоматизированна подготовка окружения приложения
- Ключевые данные вынесены в переменные packer

## Как запустить проект:
- Следовать инструкциям из README.md

## Как проверить работоспособность:
- Выполнить последовательность действий из README.md

## PR checklist
- [ ] Выставил label с номером домашнего задания
- [x] Выставил label с темой домашнего задания

2022-04-08 08:46 UTC, he110 commented
Добрый день! Посмотрел, почему тесты упали. Не может найти сервисный ключ, но его по условиям дз не должно быть в репозитории

2022-04-08 09:11 UTC, mrgreyves requested changes
Здравствуйте!)
Все так, но фейковый ключ то может быть в репозитории =)
Нужно добавить его, выглядит как приключение на 10 минут =)

2022-04-08 09:12 UTC, he110 commented
> Здравствуйте!)
> 
> Все так, но фейковый ключ то может быть в репозитории =)
> 
> Нужно добавить его, выглядит как приключение на 10 минут =)

Могу добавить. Но кажется что фейковый ключ в репозитории может дезинформировать

2022-04-08 09:18 UTC, mrgreyves commented
Кажется что да
Но сейчас мы рассматриваем ситуацию с тестами
Если в реально среде, то ключи могут "подкидываться" из секретов =)

2022-04-12 18:04 UTC, he110 commented
Добавил фейковый key.json

2022-04-13 08:25 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-04-13 12:00 UTC, merged